//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrocolsaAccesoDatosNet {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SentenciasMsSqlB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SentenciasMsSqlB() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrocolsaAccesoDatosNet.SentenciasMsSqlB", typeof(SentenciasMsSqlB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT NAME NOMBRE_CAMPO FROM SYSCOLUMNS WHERE ID IN(SELECT ID FROM SYSOBJECTS WHERE NAME=@TABLA).
        /// </summary>
        internal static string CAMPOS_TABLA {
            get {
                return ResourceManager.GetString("CAMPOS_TABLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT SYSCOLUMNS.NAME NOMBRE_ARGUMENTO,SYSTYPES.NAME TIPO_DATO, SYSCOLUMNS.ISOUTPARAM DIRECCION,UPPER(SYSTYPES.NAME) TIPO_DATO, SYSCOLUMNS.LENGTH TAMANO, SYSCOLUMNS.COLORDER POSICION
        ///FROM SYSCOLUMNS
        ///INNER JOIN SYSTYPES ON (SYSCOLUMNS.XTYPE=SYSTYPES.XTYPE)
        ///WHERE ID IN (SELECT ID FROM SYSOBJECTS WHERE  SYSOBJECTS.NAME =@PROCEDIMIENTO) 
        ///ORDER BY SYSCOLUMNS.COLORDER.
        /// </summary>
        internal static string PARAMETROS_PROCEDIMIENTOS_ALMACENADOS {
            get {
                return ResourceManager.GetString("PARAMETROS_PROCEDIMIENTOS_ALMACENADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT NAME PROCEDIMIENTO FROM SYSOBJECTS WHERE XTYPE = &apos;P&apos; ORDER BY NAME;.
        /// </summary>
        internal static string PROCEDIMIENTOS_ALMACENADOS {
            get {
                return ResourceManager.GetString("PROCEDIMIENTOS_ALMACENADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT NAME TABLA FROM SYSOBJECTS WHERE XTYPE=&apos;U&apos; ORDER BY TABLA.
        /// </summary>
        internal static string TABLAS_BASEDATOS {
            get {
                return ResourceManager.GetString("TABLAS_BASEDATOS", resourceCulture);
            }
        }
    }
}
